targets:
  $default:
    builders:
      artemis:
        options:
          schema_mapping:
            - schema: lib/graphql/todo.schema.graphql
              queries_glob: lib/graphql/todo.query.graphql
              output: lib/graphql/generated/todo.query.dart
          custom_parser_import: 'package:flutter_todo/coercers.dart'
          scalar_mapping:
          - graphql_type: Date
            dart_type: DateTime
            use_custom_parser: true
          - graphql_type: Time
            dart_type: DateTime
            use_custom_parser: true
          - graphql_type: DateTime
            dart_type: DateTime
            use_custom_parser: true
          - graphql_type: DiscID
            dart_type: String
          - graphql_type: MBID
            dart_type: String
          - graphql_type: ASIN
            dart_type: String
          - graphql_type: IPI
            dart_type: String
          - graphql_type: ISNI
            dart_type: String
          - graphql_type: ISRC
            dart_type: String
          - graphql_type: URLString
            dart_type: String
          - graphql_type: Degrees
            dart_type: double
          - graphql_type: Locale
            dart_type: String